version: "3.8"
services:
  webserver:
    build: .
    entrypoint: ["python", "/usr/src/app/entrypoint.py"]
    volumes:
      - ./monitoring_app_web_application/:/usr/src/app/
    ports:
      - "8080-8082:8080-8082"
    env_file:
      - ./dev.env
    depends_on:
      - databases

  databases:
    image: postgres:12.4-alpine
    ports:
      - 8083:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cryptocurrency_app_dev
  
  pgadmin:
    image: dpage/pgadmin4:4.26
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8084:80
    depends_on:
      - databases
    volumes: 
      - pgadmin_data:/var/lib/pgadmin/

volumes:
  postgres_data:
  pgadmin_data:
