version: "3.8"
services:
  webserver:
    build: .
    entrypoint: ["python", "/usr/src/app/entrypoint.py"]
    volumes:
      - ./monitoring_web_application/:/usr/src/app/
    ports:
      - "8080-8082:8080-8082"
    env_file:
      - ./dev.env
    depends_on:
      - databases

  databases:
    image: postgres:12.5-alpine
    ports:
      - "8083-8084:5432-5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cryptocurrency_app_dev
  
  pgadmin:
    image: dpage/pgadmin4:4.28
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8085:80
    depends_on:
      - databases
    volumes: 
      - pgadmin_data:/var/lib/pgadmin/

volumes:
  postgres_data:
  pgadmin_data:
